apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: imperio-gateway
  name: imperio-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imperio-gateway
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: imperio-gateway
    spec:
      containers:
        - image: finda/imperio-gateway
          imagePullPolicy: Always
          name: imperio-gateway
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: imperio-gateway
spec:
  ports:
    - port: 8000
      name: http
      targetPort: 80
  selector:
    app: imperio-gateway
