server:
  port: 80

infrastructure:
  instances:
    host: instances.imperio
    service: imperio-instances
    port: 9001
  auth:
    port: 8080

spring:
  application:
    name: imperio-gateway
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
  devtools:
    restart:
      enabled: false

management:
  server:
    port: 80
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
