server:
  port: 80

infrastructure:
  tls:
    key-store-type: pkcs12
    key-store: src/main/resources/keystore.p12
    key-store-password: imperio
    ca: src/main/resources/ca.p12
    ca-password: imperio
  instances:
    host: https://instances.imperio
    service: imperio-instances
    port: 443
  auth:
    port: 8080

spring:
  application:
    name: imperio-gateway
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
  devtools:
    restart:
      enabled: false

management:
  server:
    port: 80
    ssl:
      enabled: false
      trust-certificate: imperio.crt
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
